inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/cache/**/*'

  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false
  Max: 80

# Allow both single-quoted and double-quoted string literals.
Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/MultilineMethodCallIndentation:
  EnforcedStyle: indented

# Allowing trailing commas decreases git churn
Style/TrailingCommaInLiteral:
  Enabled: false
Style/TrailingCommaInArguments:
  Enabled: false

# Allow non-alphabetical Gemfiles.
Bundler/OrderedGems:
  Enabled: false
