inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.4

Metrics/LineLength:
  Enabled: false
  Max: 80

Metrics/ModuleLength:
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# Allow both single-quoted and double-quoted string literals.
Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/SignalException:
  Exclude:
    - 'config/initializers/warden.rb'

# Allow non-alphabetical Gemfiles.
Bundler/OrderedGems:
  Enabled: false
