inherit_from: .rubocop_todo.yml

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'
    - 'vendor/cache/**/*'

  TargetRubyVersion: 2.3

Metrics/LineLength:
  Enabled: false
  Max: 80

Style/StringLiterals:
  EnforcedStyle: double_quotes
  Enabled: false

Style/Documentation:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/AlignHash:
  # EnforcedStyle: with_fixed_indentation
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation
